(()=>{
  const $=id=>document.getElementById(id);
  const SETTINGS_KEY='leagueSpeakerManagement.settings.v2';
  const headers=['Event Name','Event Start Date','Event End Date','Event Location','Event Status','Event Owner','First Name','Last Name','Email','Title','Organization','Speaker Status','Session Title','Session Date','Session Time','Room','Bio Status','Headshot Status','Slides Status','AV Needs','Registration Status','Logistics Status','Internal Owner','Notes'];
  const templates={
    invitation:{subject:'Invitation to present at {{event_name}}',body:'{{first_name}},\n\nWe would like to invite you to present at {{event_name}}. Your proposed session is “{{session_title}}.”\n\nPlease reply to confirm whether you are available to participate.\n\nThank you,'},
    materials:{subject:'{{event_name}} speaker materials',body:'{{first_name}},\n\nWe are preparing final speaker materials for {{event_name}} and are following up on your session, “{{session_title}}.”\n\nPlease send any outstanding speaker materials at your earliest convenience.\n\nThank you,'},
    logistics:{subject:'Final logistics for {{event_name}}',body:'{{first_name}},\n\nBelow are the final details for your session at {{event_name}}.\n\nSession: {{session_title}}\nDate: {{session_date}}\nTime: {{session_time}}\nRoom: {{room}}\n\nThank you for joining us as a presenter.'},
    thanks:{subject:'Thank you for presenting at {{event_name}}',body:'{{first_name}},\n\nThank you for presenting at {{event_name}}. We appreciate the time and expertise you shared with our members through “{{session_title}}.”\n\nThank you,'},
    custom:{subject:'',body:''}
  };
  let state={events:[],speakers:[],communications:[]};
  let settings=loadSettings();

  function loadSettings(){try{return{fromName:'',fromEmail:'',...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return{fromName:'',fromEmail:''}}}
  function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}
  function uid(prefix='id'){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`}
  function norm(v){return String(v??'').trim()}
  function low(v){return norm(v).toLowerCase()}
  function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
  function eventById(id){return state.events.find(e=>e.id===id)}
  function fmtDate(v){if(!v)return'';const d=new Date(v+'T12:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
  function readiness(s){return [s.bioStatus&&s.bioStatus!=='Missing',s.headshotStatus&&s.headshotStatus!=='Missing',!['Missing',''].includes(s.slidesStatus),['Complete','Not required'].includes(s.registrationStatus),['Sent','Acknowledged'].includes(s.logisticsStatus)].filter(Boolean).length}
  function needsAttention(s){return !['Declined','Complete'].includes(s.speakerStatus)&&readiness(s)<5}

  async function api(path,options={}){
    const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});
    let body;try{body=await r.json()}catch{body={ok:false,error:`Non-JSON response (${r.status})`}}
    if(!r.ok||body.ok===false)throw new Error(body.error||`Request failed (${r.status})`);
    return body;
  }
  function setBusy(on){$('appShell').classList.toggle('loading',on)}
  function setConnection(ok,text){$('connectionDot').className='dot '+(ok?'ok':'bad');$('connectionText').textContent=text;$('connectionDetail').className='notice '+(ok?'':'error');$('connectionDetail').textContent=ok?'Cloudflare bridge and Jotform shared data are connected.':'Connection problem: '+text}
  async function loadSharedState(showNotice=false){setBusy(true);try{const data=await api('/api/state');state=data.state||{};state.events=state.events||[];state.speakers=state.speakers||[];state.communications=state.communications||[];setConnection(true,'Shared data connected');if(showNotice)$('globalNotice').innerHTML='<div class="notice">Shared data refreshed.</div>';renderAll()}catch(e){setConnection(false,e.message);$('globalNotice').innerHTML=`<div class="notice error"><strong>Could not load shared data.</strong> ${esc(e.message)}</div>`;renderAll()}finally{setBusy(false)}}
  async function writeRecord(type,record){const payload={...record};delete payload.id;return api('/api/record',{method:'POST',body:JSON.stringify({type,id:record.id,payload})})}
  async function removeRecord(type,id){return api(`/api/record?type=${encodeURIComponent(type)}&id=${encodeURIComponent(id)}`,{method:'DELETE'})}

  const pageMeta={dashboard:['Dashboard','Speaker readiness across all active events'],events:['Events','Manage multiple conferences, trainings, and programs'],speakers:['Speakers','Maintain speaker and session records'],import:['Import / Export','Bulk load, update, and export speaker information'],email:['Email Center','Prepare speaker communications by event and status'],settings:['Settings','Connection and browser preferences']};
  function showView(name){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$('pageTitle').textContent=pageMeta[name][0];$('pageSubtitle').textContent=pageMeta[name][1]}
  function badge(value){const success=['Active','Ready','Complete','Approved','Received','Sent','Acknowledged','Confirmed'].includes(value),danger=value==='Declined',warning=['Planning','Invited','Missing','Not sent','Not started'].includes(value);return `<span class="badge ${success?'success':danger?'danger':warning?'warning':'neutral'}">${esc(value||'—')}</span>`}
  function renderAll(){renderDashboard();renderEvents();renderSpeakers();populateEventSelects();renderRecipients();renderSettings()}

  function renderDashboard(){
    const active=state.events.filter(e=>['Planning','Active'].includes(e.status)).length,total=state.speakers.length,ready=state.speakers.filter(s=>s.speakerStatus==='Ready'||readiness(s)===5).length,attention=state.speakers.filter(needsAttention).length;
    $('dashboardCards').innerHTML=[['Active events',active,'Planning or active'],['Speakers',total,'Across all events'],['Ready',ready,'All readiness items complete'],['Needs attention',attention,'At least one readiness item missing']].map(([l,v,s])=>`<div class="card"><div class="label">${l}</div><div class="value">${v}</div><div class="sub">${s}</div></div>`).join('');
    $('eventReadiness').innerHTML=state.events.length?`<table><thead><tr><th>Event</th><th>Dates</th><th>Status</th><th>Speakers</th><th>Ready</th><th>Needs attention</th></tr></thead><tbody>${state.events.map(e=>{const ss=state.speakers.filter(s=>s.eventId===e.id);return `<tr><td><strong>${esc(e.name)}</strong><br><span class="muted">${esc(e.location||'')}</span></td><td>${esc(fmtDate(e.startDate))}${e.endDate&&e.endDate!==e.startDate?' – '+esc(fmtDate(e.endDate)):''}</td><td>${badge(e.status)}</td><td>${ss.length}</td><td>${ss.filter(s=>s.speakerStatus==='Ready'||readiness(s)===5).length}</td><td>${ss.filter(needsAttention).length}</td></tr>`}).join('')}</tbody></table>`:'<div class="empty">No events yet. Add an event to begin.</div>';
    const items=state.speakers.filter(needsAttention).slice(0,12);
    $('attentionList').innerHTML=items.length?`<table><thead><tr><th>Speaker</th><th>Event</th><th>Session</th><th>Outstanding</th></tr></thead><tbody>${items.map(s=>{const m=[];if(!s.bioStatus||s.bioStatus==='Missing')m.push('Bio');if(!s.headshotStatus||s.headshotStatus==='Missing')m.push('Headshot');if(!s.slidesStatus||s.slidesStatus==='Missing')m.push('Slides');if(!['Complete','Not required'].includes(s.registrationStatus))m.push('Registration');if(!['Sent','Acknowledged'].includes(s.logisticsStatus))m.push('Logistics');return `<tr><td><strong>${esc(s.firstName)} ${esc(s.lastName)}</strong></td><td>${esc(eventById(s.eventId)?.name||'')}</td><td>${esc(s.sessionTitle)}</td><td>${m.map(x=>`<span class="badge warning">${x}</span>`).join(' ')}</td></tr>`}).join('')}</tbody></table>`:'<div class="empty">No speaker records currently need attention.</div>';
  }
  function renderEvents(){const el=$('eventsTable');if(!state.events.length){el.innerHTML='<div class="empty">No events yet.</div>';return}el.innerHTML=`<table><thead><tr><th>Event</th><th>Dates</th><th>Location</th><th>Status</th><th>Owner</th><th>Speakers</th><th></th></tr></thead><tbody>${state.events.map(e=>`<tr><td><strong>${esc(e.name)}</strong></td><td>${esc(fmtDate(e.startDate))}${e.endDate&&e.endDate!==e.startDate?' – '+esc(fmtDate(e.endDate)):''}</td><td>${esc(e.location||'')}</td><td>${badge(e.status)}</td><td>${esc(e.owner||'')}</td><td>${state.speakers.filter(s=>s.eventId===e.id).length}</td><td><button class="btn small" onclick="window.SM.editEvent('${e.id}')">Edit</button> <button class="btn small danger" onclick="window.SM.deleteEvent('${e.id}')">Delete</button></td></tr>`).join('')}</tbody></table>`}
  function renderSpeakers(){const ef=$('speakerEventFilter').value,sf=$('speakerStatusFilter').value,q=low($('speakerSearch').value);let ss=[...state.speakers];if(ef)ss=ss.filter(s=>s.eventId===ef);if(sf)ss=ss.filter(s=>s.speakerStatus===sf);if(q)ss=ss.filter(s=>[s.firstName,s.lastName,s.email,s.organization,s.sessionTitle,eventById(s.eventId)?.name].some(v=>low(v).includes(q)));const el=$('speakersTable');if(!ss.length){el.innerHTML='<div class="empty">No speakers match the current filters.</div>';return}el.innerHTML=`<table><thead><tr><th>Speaker</th><th>Event</th><th>Session</th><th>Status</th><th>Bio</th><th>Headshot</th><th>Slides</th><th>Registration</th><th>Logistics</th><th></th></tr></thead><tbody>${ss.map(s=>`<tr><td><strong>${esc(s.firstName)} ${esc(s.lastName)}</strong><br><span class="muted">${esc(s.organization||'')}<br>${esc(s.email)}</span></td><td>${esc(eventById(s.eventId)?.name||'')}</td><td>${esc(s.sessionTitle)}<br><span class="muted">${esc(fmtDate(s.sessionDate))} ${esc(s.sessionTime||'')}</span></td><td>${badge(s.speakerStatus)}</td><td>${badge(s.bioStatus)}</td><td>${badge(s.headshotStatus)}</td><td>${badge(s.slidesStatus)}</td><td>${badge(s.registrationStatus)}</td><td>${badge(s.logisticsStatus)}</td><td><button class="btn small" onclick="window.SM.editSpeaker('${s.id}')">Edit</button> <button class="btn small danger" onclick="window.SM.deleteSpeaker('${s.id}')">Delete</button></td></tr>`).join('')}</tbody></table>`}
  function populateEventSelects(){['speakerEventFilter','speakerEventId','emailEventFilter'].forEach(id=>{const s=$(id),prior=s.value,first=id==='speakerEventFilter'?'<option value="">All events</option>':'<option value="">Choose an event</option>';s.innerHTML=first+state.events.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');if([...s.options].some(o=>o.value===prior))s.value=prior})}

  function openEventDialog(e=null){$('eventDialogTitle').textContent=e?'Edit event':'Add event';$('eventId').value=e?.id||'';$('eventName').value=e?.name||'';$('eventStartDate').value=e?.startDate||'';$('eventEndDate').value=e?.endDate||'';$('eventLocation').value=e?.location||'';$('eventStatus').value=e?.status||'Planning';$('eventOwner').value=e?.owner||'';$('eventDialog').showModal()}
  async function saveEvent(){const name=norm($('eventName').value);if(!name)return alert('Event name is required.');const record={id:$('eventId').value||uid('evt'),name,startDate:$('eventStartDate').value,endDate:$('eventEndDate').value,location:norm($('eventLocation').value),status:$('eventStatus').value,owner:norm($('eventOwner').value)};$('saveEventBtn').disabled=true;try{await writeRecord('event',record);$('eventDialog').close();await loadSharedState()}catch(e){alert('Could not save event: '+e.message)}finally{$('saveEventBtn').disabled=false}}
  function openSpeakerDialog(s=null){if(!state.events.length){alert('Create an event before adding speakers.');showView('events');return}populateEventSelects();$('speakerDialogTitle').textContent=s?'Edit speaker':'Add speaker';const vals={speakerId:s?.id||'',speakerEventId:s?.eventId||state.events[0]?.id||'',speakerFirstName:s?.firstName||'',speakerLastName:s?.lastName||'',speakerEmail:s?.email||'',speakerTitle:s?.title||'',speakerOrganization:s?.organization||'',speakerStatus:s?.speakerStatus||'Invited',speakerSessionTitle:s?.sessionTitle||'',speakerSessionDate:s?.sessionDate||'',speakerSessionTime:s?.sessionTime||'',speakerRoom:s?.room||'',speakerBioStatus:s?.bioStatus||'Missing',speakerHeadshotStatus:s?.headshotStatus||'Missing',speakerSlidesStatus:s?.slidesStatus||'Missing',speakerAvNeeds:s?.avNeeds||'',speakerRegistrationStatus:s?.registrationStatus||'Not started',speakerLogisticsStatus:s?.logisticsStatus||'Not sent',speakerOwner:s?.owner||'',speakerNotes:s?.notes||''};Object.entries(vals).forEach(([id,v])=>$(id).value=v);$('speakerDialog').showModal()}
  async function saveSpeaker(){const required=['speakerEventId','speakerFirstName','speakerLastName','speakerEmail','speakerSessionTitle'];if(required.some(id=>!norm($(id).value)))return alert('Event, first name, last name, email, and session title are required.');const record={id:$('speakerId').value||uid('spk'),eventId:$('speakerEventId').value,firstName:norm($('speakerFirstName').value),lastName:norm($('speakerLastName').value),email:norm($('speakerEmail').value),title:norm($('speakerTitle').value),organization:norm($('speakerOrganization').value),speakerStatus:$('speakerStatus').value,sessionTitle:norm($('speakerSessionTitle').value),sessionDate:$('speakerSessionDate').value,sessionTime:norm($('speakerSessionTime').value),room:norm($('speakerRoom').value),bioStatus:$('speakerBioStatus').value,headshotStatus:$('speakerHeadshotStatus').value,slidesStatus:$('speakerSlidesStatus').value,avNeeds:norm($('speakerAvNeeds').value),registrationStatus:$('speakerRegistrationStatus').value,logisticsStatus:$('speakerLogisticsStatus').value,owner:norm($('speakerOwner').value),notes:norm($('speakerNotes').value)};$('saveSpeakerBtn').disabled=true;try{await writeRecord('speaker',record);$('speakerDialog').close();await loadSharedState()}catch(e){alert('Could not save speaker: '+e.message)}finally{$('saveSpeakerBtn').disabled=false}}
  async function deleteSpeaker(id){if(!confirm('Delete this speaker record?'))return;try{await removeRecord('speaker',id);await loadSharedState()}catch(e){alert('Could not delete speaker: '+e.message)}}
  async function deleteEvent(id){const e=eventById(id),linked=state.speakers.filter(s=>s.eventId===id);if(!confirm(`Delete ${e?.name||'this event'} and ${linked.length} associated speaker record(s)?`))return;try{for(const s of linked)await removeRecord('speaker',s.id);await removeRecord('event',id);await loadSharedState()}catch(err){alert('Could not complete delete: '+err.message);await loadSharedState()}}

  function downloadTemplate(){if(!window.XLSX)return alert('Excel library did not load.');const sample={};headers.forEach(h=>sample[h]='');Object.assign(sample,{'Event Name':'Example Event','Event Status':'Planning','First Name':'Jane','Last Name':'Smith','Email':'jane@example.org','Speaker Status':'Invited','Session Title':'Example Session','Bio Status':'Missing','Headshot Status':'Missing','Slides Status':'Missing','Registration Status':'Not started','Logistics Status':'Not sent'});const ws=XLSX.utils.json_to_sheet([sample],{header:headers});ws['!cols']=headers.map(h=>({wch:Math.max(14,Math.min(26,h.length+4))}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Speakers');XLSX.writeFile(wb,'League_Speaker_Management_Template.xlsx')}
  function speakerToRow(s){const e=eventById(s.eventId)||{};return{'Event Name':e.name||'','Event Start Date':e.startDate||'','Event End Date':e.endDate||'','Event Location':e.location||'','Event Status':e.status||'','Event Owner':e.owner||'','First Name':s.firstName||'','Last Name':s.lastName||'','Email':s.email||'','Title':s.title||'','Organization':s.organization||'','Speaker Status':s.speakerStatus||'','Session Title':s.sessionTitle||'','Session Date':s.sessionDate||'','Session Time':s.sessionTime||'','Room':s.room||'','Bio Status':s.bioStatus||'','Headshot Status':s.headshotStatus||'','Slides Status':s.slidesStatus||'','AV Needs':s.avNeeds||'','Registration Status':s.registrationStatus||'','Logistics Status':s.logisticsStatus||'','Internal Owner':s.owner||'','Notes':s.notes||''}}
  function exportData(){if(!window.XLSX)return alert('Excel library did not load.');const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.speakers.map(speakerToRow),{header:headers}),'Speakers');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.events.map(e=>({'Event Name':e.name,'Start Date':e.startDate,'End Date':e.endDate,'Location':e.location,'Status':e.status,'Owner':e.owner}))),'Events');XLSX.writeFile(wb,`League_Speaker_Data_${new Date().toISOString().slice(0,10)}.xlsx`)}
  function nonblank(v,current){const n=norm(v);return n?n:(current||'')}
  function defaultsFor(prop){return({speakerStatus:'Invited',bioStatus:'Missing',headshotStatus:'Missing',slidesStatus:'Missing',registrationStatus:'Not started',logisticsStatus:'Not sent'})[prop]||''}
  function excelDate(v){if(!v)return'';if(typeof v==='number'&&window.XLSX){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:''}const s=norm(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toISOString().slice(0,10)}
  async function importExcel(file){const result=$('importResult');if(!file)return;if(!window.XLSX){result.innerHTML='<div class="notice error">Excel library did not load.</div>';return}try{result.innerHTML='<div class="notice">Preparing shared import…</div>';const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});if(!rows.length)throw new Error('The first worksheet contains no data rows.');const missing=['Event Name','First Name','Last Name','Email','Session Title'].filter(h=>!(h in rows[0]));if(missing.length)throw new Error(`Missing required header(s): ${missing.join(', ')}`);
    const workingEvents=state.events.map(e=>({...e})),workingSpeakers=state.speakers.map(s=>({...s}));const changedEvents=new Map(),changedSpeakers=new Map();let added=0,updated=0,skipped=0,newEvents=0;
    for(const row of rows){const eventName=norm(row['Event Name']),email=norm(row['Email']),sessionTitle=norm(row['Session Title']);if(!eventName||!email||!sessionTitle||!norm(row['First Name'])||!norm(row['Last Name'])){skipped++;continue}let event=workingEvents.find(e=>low(e.name)===low(eventName));if(!event){event={id:uid('evt'),name:eventName,startDate:excelDate(row['Event Start Date']),endDate:excelDate(row['Event End Date']),location:norm(row['Event Location']),status:norm(row['Event Status'])||'Planning',owner:norm(row['Event Owner'])};workingEvents.push(event);changedEvents.set(event.id,event);newEvents++}else{const before=JSON.stringify(event);event.startDate=nonblank(excelDate(row['Event Start Date']),event.startDate);event.endDate=nonblank(excelDate(row['Event End Date']),event.endDate);event.location=nonblank(row['Event Location'],event.location);event.status=nonblank(row['Event Status'],event.status);event.owner=nonblank(row['Event Owner'],event.owner);if(JSON.stringify(event)!==before)changedEvents.set(event.id,event)}const existing=workingSpeakers.find(s=>s.eventId===event.id&&low(s.email)===low(email)&&low(s.sessionTitle)===low(sessionTitle));const target=existing||{id:uid('spk'),eventId:event.id};const map={firstName:'First Name',lastName:'Last Name',email:'Email',title:'Title',organization:'Organization',speakerStatus:'Speaker Status',sessionTitle:'Session Title',sessionTime:'Session Time',room:'Room',bioStatus:'Bio Status',headshotStatus:'Headshot Status',slidesStatus:'Slides Status',avNeeds:'AV Needs',registrationStatus:'Registration Status',logisticsStatus:'Logistics Status',owner:'Internal Owner',notes:'Notes'};Object.entries(map).forEach(([prop,col])=>{const val=norm(row[col]);if(val||!existing)target[prop]=val||defaultsFor(prop)});const sd=excelDate(row['Session Date']);if(sd||!existing)target.sessionDate=sd;if(existing)updated++;else{workingSpeakers.push(target);added++}changedSpeakers.set(target.id,target)}
    const records=[...changedEvents.values()].map(e=>{const payload={...e};delete payload.id;return{type:'event',id:e.id,payload}}).concat([...changedSpeakers.values()].map(s=>{const payload={...s};delete payload.id;return{type:'speaker',id:s.id,payload}}));
    for(let i=0;i<records.length;i+=100){result.innerHTML=`<div class="notice">Saving shared records ${i+1}–${Math.min(i+100,records.length)} of ${records.length}…</div>`;await api('/api/batch',{method:'POST',body:JSON.stringify({records:records.slice(i,i+100)})})}
    await loadSharedState();result.innerHTML=`<div class="notice"><strong>Import complete.</strong> ${added} speaker(s) added, ${updated} updated, ${newEvents} event(s) created, ${skipped} row(s) skipped.</div>`;
  }catch(e){result.innerHTML=`<div class="notice error"><strong>Import failed.</strong> ${esc(e.message)}</div>`}finally{$('excelUpload').value=''}}

  function renderRecipients(){const eventId=$('emailEventFilter').value,status=$('emailStatusFilter').value,el=$('recipientList');if(!eventId){el.innerHTML='<div class="empty">Choose an event to load speakers.</div>';return}let ss=state.speakers.filter(s=>s.eventId===eventId&&s.email);if(status)ss=ss.filter(s=>s.speakerStatus===status);el.innerHTML=ss.length?ss.map(s=>`<label class="recipient-row"><input class="recipientCheck" type="checkbox" value="${s.id}" checked><span><strong>${esc(s.firstName)} ${esc(s.lastName)}</strong><br><span class="muted">${esc(s.email)} · ${esc(s.sessionTitle)}</span></span></label>`).join(''):'<div class="empty">No speakers match this selection.</div>'}
  function selectedRecipients(){return [...document.querySelectorAll('.recipientCheck:checked')].map(c=>state.speakers.find(s=>s.id===c.value)).filter(Boolean)}
  function merge(text,s){const e=eventById(s.eventId)||{},f={first_name:s.firstName,last_name:s.lastName,event_name:e.name,session_title:s.sessionTitle,session_date:fmtDate(s.sessionDate),session_time:s.sessionTime,room:s.room};return String(text||'').replace(/\{\{(\w+)\}\}/g,(_,k)=>f[k]??'')}
  function applyTemplate(k){const t=templates[k];$('emailSubject').value=t.subject;$('emailBody').value=t.body}
  function previewEmail(){const s=selectedRecipients()[0];if(!s)return alert('Select at least one recipient.');$('emailPreview').textContent=`To: ${s.email}\nSubject: ${merge($('emailSubject').value,s)}\n\n${merge($('emailBody').value,s)}`;$('emailPreviewWrap').classList.remove('hidden')}
  function openEmailClient(){const recipients=selectedRecipients();if(!recipients.length)return alert('Select at least one recipient.');if(recipients.length>1){const subject=$('emailSubject').value,body=$('emailBody').value;if(/\{\{/.test(subject+body))return alert('For personalized merge fields, select one speaker at a time until direct Jotform sending is enabled.');location.href=`mailto:?bcc=${encodeURIComponent(recipients.map(s=>s.email).join(','))}&subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;return}const s=recipients[0];location.href=`mailto:${encodeURIComponent(s.email)}?subject=${encodeURIComponent(merge($('emailSubject').value,s))}&body=${encodeURIComponent(merge($('emailBody').value,s))}`}
  function renderSettings(){$('settingFromName').value=settings.fromName||'';$('settingFromEmail').value=settings.fromEmail||''}

  document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
  $('refreshDataBtn').onclick=()=>loadSharedState(true);$('settingsRefreshBtn').onclick=()=>loadSharedState(true);
  $('addEventBtn').onclick=()=>openEventDialog();$('saveEventBtn').onclick=saveEvent;
  $('addSpeakerBtn').onclick=()=>openSpeakerDialog();$('quickAddSpeaker').onclick=()=>openSpeakerDialog();$('saveSpeakerBtn').onclick=saveSpeaker;
  $('speakerEventFilter').onchange=renderSpeakers;$('speakerStatusFilter').onchange=renderSpeakers;$('speakerSearch').oninput=renderSpeakers;
  $('downloadTemplateBtn').onclick=downloadTemplate;$('exportDataBtn').onclick=exportData;$('excelUpload').onchange=e=>importExcel(e.target.files[0]);
  $('emailEventFilter').onchange=renderRecipients;$('emailStatusFilter').onchange=renderRecipients;$('emailTemplate').onchange=e=>applyTemplate(e.target.value);$('previewEmailBtn').onclick=previewEmail;$('openEmailClientBtn').onclick=openEmailClient;
  $('saveSettingsBtn').onclick=()=>{settings={fromName:norm($('settingFromName').value),fromEmail:norm($('settingFromEmail').value)};saveSettings();renderSettings();alert('Defaults saved.')};
  window.SM={editEvent:id=>openEventDialog(eventById(id)),deleteEvent,editSpeaker:id=>openSpeakerDialog(state.speakers.find(s=>s.id===id)),deleteSpeaker};
  applyTemplate('materials');renderSettings();renderAll();loadSharedState();
})();