(()=>{
const $=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#039;','"':'&quot;'}[c])),M='application/vnd.openxmlformats-officedocument.wordprocessingml.document';
const api=async(u,o={})=>{const r=await fetch(u,o),b=await r.json().catch(()=>({error:`Unexpected response (${r.status})`}));if(!r.ok||b.ok===false)throw Error(b.error||`Request failed (${r.status})`);return b};
const state=async()=>{const b=await api('/api/state'),s=b.state||{};return{events:s.events||[],sessions:s.sessions||[],speakers:s.speakers||[]}};
const d=v=>{if(!v)return null;const x=new Date(v+'T12:00:00');return isNaN(x)?null:x},sd=v=>d(v)?.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})||'';
function range(e){const a=d(e.startDate),b=d(e.endDate);if(!a&&!b)return'';if(!a||!b)return(a||b).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'});if(a.toDateString()===b.toDateString())return a.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'});if(a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth())return`${a.toLocaleDateString('en-US',{month:'long'})} ${a.getDate()}–${b.getDate()}, ${a.getFullYear()}`;return`${a.toLocaleDateString('en-US',{month:'long',day:'numeric'})}–${b.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}`}
function blob(b,n){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function name(s){return(String(s||'Program Flow').replace(/[\\/:*?"<>|]+/g,'-').trim()||'Program Flow')}
function text(buf){const z=new PizZip(buf),x=z.file('word/document.xml')?.asText()||'';return x.replace(/<[^>]*>/g,'')}
function valid(buf){let t;try{t=text(buf)}catch{throw Error('This file is not a readable DOCX template.')}const m=['{#sessions}','{/sessions}','{session_title}'].filter(x=>!t.includes(x));if(m.length)throw Error(`Template is missing: ${m.join(', ')}. Use the starter template and preserve its session row tags.`)}
function program(s,id){const e=s.events.find(x=>x.id===id);if(!e)throw Error('Event not found.');const ss=s.sessions.filter(x=>x.eventId===id).sort((a,b)=>(a.date||'').localeCompare(b.date||'')||(a.time||'').localeCompare(b.time||'')||(a.title||'').localeCompare(b.title||''));return{event_name:e.name||'',event_location:e.location||'',event_dates:range(e),sessions:ss.map(x=>({session_date:sd(x.date),session_time:x.time||'',session_title:x.title||'',room:x.room||'',speakers:s.speakers.filter(p=>p.sessionId===x.id&&p.speakerStatus!=='Declined').map(p=>[`${p.firstName||''} ${p.lastName||''}`.trim(),p.title,p.organization].filter(Boolean).join(', ')).join('\n')}))}}
function msg(h,bad=false){const x=$('pfMsg');x.className=bad?'notice error':'notice';x.innerHTML=h;x.classList.remove('hidden')}
function buttons(ev,has){$('pfUpload').disabled=!ev;$('pfGenerate').disabled=!ev;$('pfGet').disabled=!has;$('pfRemove').disabled=!has}
async function status(){const id=$('pfEvent').value,s=$('pfStatus');if(!id){s.textContent='Choose an event.';buttons(false,false);return}try{const m=await api(`/api/program-template?eventId=${encodeURIComponent(id)}&meta=1`);s.innerHTML=m.exists?`Uploaded: <strong>${E(m.filename)}</strong>`:'No custom template. The starter template will be used.';buttons(true,!!m.exists)}catch(e){s.textContent=e.message;buttons(false,false)}}
async function events(){const p=$('pfEvent').value,s=await state();$('pfEvent').innerHTML='<option value="">Choose an event</option>'+s.events.map(e=>`<option value="${E(e.id)}">${E(e.name)}</option>`).join('');if(s.events.some(e=>e.id===p))$('pfEvent').value=p;status()}
async function upload(){const id=$('pfEvent').value,f=$('pfFile').files[0];if(!id||!f)return alert('Choose an event and a DOCX template.');if(!/\.docx$/i.test(f.name)||f.size>10485760)return alert('Use a .docx file under 10 MB.');const b=await f.arrayBuffer();try{valid(b);const r=await fetch(`/api/program-template?eventId=${encodeURIComponent(id)}`,{method:'POST',headers:{'content-type':M,'x-file-name':encodeURIComponent(f.name)},body:b}),j=await r.json();if(!r.ok||j.ok===false)throw Error(j.error||'Upload failed.');$('pfFile').value='';msg(`<strong>Template saved.</strong> ${E(f.name)}`);status()}catch(e){msg(`<strong>Could not upload template.</strong> ${E(e.message)}`,true)}}
async function getTpl(){const id=$('pfEvent').value,r=await fetch(`/api/program-template?eventId=${encodeURIComponent(id)}`);if(!r.ok)return alert((await r.json().catch(()=>({}))).error||'Could not download template.');blob(await r.blob(),'Program Flow Template.docx')}
async function remove(){const id=$('pfEvent').value;if(!confirm('Remove this event’s custom Program Flow template?'))return;try{await api(`/api/program-template?eventId=${encodeURIComponent(id)}`,{method:'DELETE'});msg('<strong>Template removed.</strong> Starter template will be used.');status()}catch(e){msg(E(e.message),true)}}
async function tpl(id){let r=await fetch(`/api/program-template?eventId=${encodeURIComponent(id)}`);if(r.ok)return r.arrayBuffer();if(r.status!==404)throw Error((await r.json().catch(()=>({}))).error||'Template could not be loaded.');r=await fetch('/program-flow-starter.docx');if(!r.ok)throw Error('Starter template unavailable.');return r.arrayBuffer()}
async function generate(){const id=$('pfEvent').value;if(!id)return;try{const s=await state(),e=s.events.find(x=>x.id===id),data=program(s,id),b=await tpl(id);valid(b);const doc=new docxtemplater(new PizZip(b),{paragraphLoop:true,linebreaks:true});doc.render(data);blob(doc.toBlob(),`${name(e?.name)} - Program Flow.docx`);msg(`<strong>Program Flow generated.</strong> ${data.sessions.length} session${data.sessions.length===1?'':'s'} and assigned speakers were populated.`)}catch(e){console.error(e);msg(`<strong>Could not generate Program Flow.</strong> ${E(e?.properties?.errors?.[0]?.properties?.explanation||e.message)}`,true)}}
function init(){const v=$('view-events'),t=v?.querySelector('.panel.table-wrap');if(!v||!t||$('programFlowPanel'))return;const p=document.createElement('div');p.className='panel';p.id='programFlowPanel';p.innerHTML=`<div class="toolbar"><div><h3 style="margin:0">Program Flow</h3><div class="hint">Create an editable Word program flow from this dashboard’s sessions and speakers.</div></div><button class="btn small" id="pfRefresh">Refresh events</button></div><div class="form-grid two"><div class="field span-2"><label>Event</label><select id="pfEvent"><option value="">Choose an event</option></select></div><div class="field span-2"><label>Program Flow template (.docx)</label><input id="pfFile" type="file" accept=".docx"><div class="hint" id="pfStatus">Choose an event.</div></div></div><div class="toolbar" style="margin-top:14px;margin-bottom:0"><div class="toolbar-left"><button class="btn" id="pfStarter">Download starter template</button><button class="btn" id="pfUpload" disabled>Upload / replace template</button><button class="btn" id="pfGet" disabled>Download uploaded template</button><button class="btn danger" id="pfRemove" disabled>Remove template</button></div><button class="btn primary" id="pfGenerate" disabled>Generate populated Program Flow</button></div><div class="notice" style="margin-top:14px">The starter uses a simple Date / Time / Activity / Room / Speakers table. Restyle it in Word as needed, but keep the template tags intact.</div><div id="pfMsg" class="hidden" style="margin-top:14px"></div>`;v.insertBefore(p,t);$('pfEvent').onchange=status;$('pfRefresh').onclick=events;$('pfStarter').onclick=()=>location.href='/program-flow-starter.docx';$('pfUpload').onclick=upload;$('pfGet').onclick=getTpl;$('pfRemove').onclick=remove;$('pfGenerate').onclick=generate;events()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
